### ISSUE TITLE
Disponibilizar as listas de exercícios

### ISSUE THREAD

**Issue by durvalcarvalho** [JudsonSS/Compiladores#1]
Em primeiro lugar, obrigado pelo material de altíssimo nível disponibilizado neste repositório!

Gostaria de saber se a lista de exercícios apresentada nos vídeos está presente em algum lugar. Eu procurei aqui no repositório e não encontrei.

**Comment by JudsonSS** [comment]
Olá Durval. Realmente não estavam disponíveis aqui no GitHub. Mas agora eu as adicionei no repositório, dentro de uma pasta "Listas".
